### ISSUE TITLE
'NoSuchMethodError' with newer versions of JS SDK

### ISSUE THREAD

**Issue by alexpaluzzi** [firebase/firebase-dart#20]
I just realized that after I updated the Firebase library to 2.0.0+, I am getting errors after all of my operations.

The calls are actually being made and showing up in the Forge, but the callbacks are failing.

I apologize if I missed a prior discussion on this, I looked in depth for one.

```
NoSuchMethodError: incorrect number of arguments passed to method named 'call'
Receiver: Closure: (dynamic, dynamic) => dynamic
Tried calling: call(null)
Found: call(err, res)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:45) (https://cdn.firebase.com/js/client/2.1.1/firebase.js:25)
Breaking on exception: Closure call with mismatched arguments: function 'call'
```

This is very easy to test. Grab the test project from this repo and change the version of the Firebase library from the CDN in `test.html` to verson `2.1.1`.

I can start working on this but I wanted to start discussion. (Not discounting the possibility I'm just doing something wrong). It worries me about backwards compatibility but I didn't see anything in the Firebase changelog that would explain it. Haven't looked deep enough.

@sethladd the ONLY thing I found on remotely similar to this issue was actually exactly the same error you were getting over a year ago on issue #3. This one isn't specific to authentication or anything, however. Thought it was worth mentioning.

**Comment by sethladd** [comment]
Happy to merge the fix. We can be explicit to developers: they will need to match a version of the pub package to a version of the JS SDK.

**Comment by madisona** [comment]
This issue should be fixed now with the firebase-dart v. 0.4.0.  The root cause was in Firebase api v. 2.0.0 several callbacks changed to only use one parameter, Error or null. The older version sent two parameters to callbacks, the first was an error, the second was usually null.

**Comment by alexpaluzzi** [comment]
Yep, this one is good to go. Great work @madisona
