### PR TITLE
Breaking: Update operations to work with latest JS SDK

### LINKED ISSUE #20: 'NoSuchMethodError' with newer versions of JS SDK
I just realized that after I updated the Firebase library to 2.0.0+, I am getting errors after all of my operations.

The calls are actually being made and showing up in the Forge, but the callbacks are failing.

I apologize if I missed a prior discussion on this, I looked in depth for one.

```
NoSuchMethodError: incorrect number of arguments passed to method named 'call'
Receiver: Closure: (dynamic, dynamic) => dynamic
Tried calling: call(null)
Found: call(err, res)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:45) (https://cdn.firebase.com/js/client/2.1.1/firebase.js:25)
Breaking on exception: Closure call with mismatched arguments: function 'call'
```

This is very easy to test. Grab the test project from this repo and change the version of the Firebase library from the CDN in `test.html` to verson `2.1.1`.

I can start working on this but I wanted to start discussion. (Not discounting the possibility I'm just doing something wrong). It worries me about backwards compatibility but I didn't see anything in the Firebase changelog that would explain it. Haven't looked deep enough.

@sethladd the ONLY thing I found on remotely similar to this issue was actually exactly the same error you were getting over a year ago on issue #3. This one isn't specific to authentication or anything, however. Thought it was worth mentioning.

### PR DESCRIPTION
**Pull request by alexpaluzzi**
This is WIP but right now is 100% passing when using latest JS lib. Fixes #20 

I need another pair of eyes who is more familiar with how the JS callbacks work in Firebase, but I wanted to begin discussion.

It seems, for the most part, a lot of the wrapper methods were passing two arguments through the callback when there should only be one. Just grabbing a random method: https://www.firebase.com/docs/web/api/firebase/update.html
`The callback will be passed an Error object on failure; else null.`

I went through the methods and removed the second argument entirely where I saw that there should never be one with the new library. I made the assumption that some of the calls might have one, so `res` now has a default value of `null` when it's going through `_resolveFuture()`.

This fixed everything but the calls using the streams-- for those, it seemed like a similar issue. Sometimes `prevChild` was going through and that was causing problems when there was no second argument. Some `.on()` events have it, some don't, so I went the optional/default route there too. See here: https://www.firebase.com/docs/web/api/query/on.html ("value" event doesn't have it, "child added" does, etc.).

As it is, this is breaking only because you would have to use the latest major version of the JS library. It requires no other code changes otherwise-- tests were untouched.

This still requires some clean-up. Methods would also need fixed in `Disconnect`. There are still a lot of deprecation warnings, etc.

Let me know if I'm also wasting my time and just doing something stupid.

### CODE REVIEW

**Comment by sethladd** [comment]
Before we merge this, can you bump the pubspec and be clear in the readme about which version of this package works with which version of the JS file?

**Comment by alexpaluzzi** [comment]
I certainly planned to. Just wanted an extra set of eyes. 

There's still some more work to do in the `Disconnect` class (where these methods are largely mirrored.) I just have to figure out how to test them. Hope to swing back around to it today and finish up.

**Comment by alexpaluzzi** [comment]
@wilsynet sorry to bother, do you see anything wrong with this strategy? I'm potentially doing something stupid. I lack Firebase experience here.

**Comment by wilsynet** [comment]
Regrettably, I also lack Firebase experience.  But let me see if I can pull in someone.  Will send an email right now.

**Comment by alexpaluzzi** [comment]
Awesome, thanks. I at least wanted to start a discussion on it.

I think we should continue to build on this library to support the entire API. I'm happy to get in there and start implementing the methods but I just think that we should take one step back and support the latest major JS version that we're wrapping before we take 10 steps forward and start sliding.

**Comment by mikelehen** [comment]
I'm familiar with Firebase, but not dart, but hopefully between us we can figure this out. :-)

The change looks reasonable to me.  In particular, your understanding that set(), update(), setPriority(), and setWithPrioirty() only pass one argument (a nullable Error object) to the callback is correct.  And the fact that prevChild may or may not exist depending on the event type is also correct.

But FWIW, these callbacks were only passed 1 argument in Firebase 1.1 as well, so I don't understand why your changes are related to moving forward to Firebase 2.1.

**Comment by sethladd** [comment]
Let me know when we should merge this.

**Comment by sethladd** [comment]
Friendly ping.

**Comment by wilsynet** [comment]
Who is the ping directed to?

**Comment by alexpaluzzi** [comment]
@wilsynet probably me. Will circle back to this sometime this week. Still needs work.

Thanks

**Comment by davenotik** [comment]
Just a note that I am coming across this myself now – firebase.dart 0.3.0 and 1.1.2 of firebase.js.

**Comment by sethladd** [comment]
Should we just merge this?

**Comment by alexpaluzzi** [comment]
@sethladd I'm looking at this right now. @davenotik said that he's seeing the same error even while using the older SDK. It needs a fresh look, I have some time to work on it today.

Will update.

**Comment by davenotik** [comment]
@alexpaluzzi I think this error happened after a "permission denied" from Firebase, and I believe it's now gone after I addressed that authentication issue. Perhaps the lib isn't failing gracefully in case of authentication errors? HTH.

**Comment by alexpaluzzi** [comment]
@davenotik that is very helpful, thanks!

I've started a fresh branch to tackle this from the beginning. Will resubmit. Closing this one.
